#ifndef PORTAL2D_GLOBAL_CONSTS_H_
#define PORTAL2D_GLOBAL_CONSTS_H_

#define PORTAL_LONG 50
#define PORTAL_WIDE 8
#define PORTAL_FLOOR_LONG 25

#define GRAVITY 0.4
#define JUMP_VEC -6
#define MOVE_VEC 3
#define MIN_TELEPORT_SPEED 5

#define PLAYER_W 20
#define PLAYER_H 40

#define MAX_PLAYER_FLOOR_SPEED 3.3
#define MAX_PLAYER_AIR_SPEED 40
#define FRICTION 0.7
#define AIR_FRICTION 0.2
#define SIDE_ACCELERATION 2
#define SIDE_AIR_ACCELERATION 0.8

#define MAX_BOX_DISTANCE 80
#define MAX_BOX_TAKE_DISTANCE 50
#define BOX_TAKED_VELOCITY_COEF 0.6

#define BOX_SIZE 23

#define FINISH_AREA_SIZE 40

#define PRESS_BUTTON_COLUMN_WIDTH 12
#define PRESS_BUTTON_COLUMN_HEIGHT 35
#define PRESS_BUTTON_HEIGHT 7
#define PRESS_BUTTON_WIDTH 10

#endif

